language: java
jdk:
- oraclejdk8

sudo: true

before_install:
  - (cd $TRAVIS_BUILD_DIR/lib/skyapi && chmod +x gradlew
  - (cd $TRAVIS_BUILD_DIR/lib/skyapi && chmod +x gradlew/wrapper/gradle-wrapper.jar

script: (cd $TRAVIS_BUILD_DIR/lib/skyapi && ./gradlew test build)