/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.Apiv1exploreraddressOutputs

/**
 * BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 * @param outputs 
 * @param innerHash 
 * @param inputs 
 * @param sigs 
 * @param length 
 * @param txid 
 * @param type 
 * @param timestamp 
 */
data class Apiv1pendingTxsTransaction (
    val outputs: kotlin.Array<Apiv1exploreraddressOutputs>? = null,
    val innerHash: kotlin.String? = null,
    val inputs: kotlin.Array<kotlin.String>? = null,
    val sigs: kotlin.Array<kotlin.String>? = null,
    val length: kotlin.Int? = null,
    val txid: kotlin.String? = null,
    val type: kotlin.Int? = null,
    val timestamp: kotlin.Int? = null
) {

}

