/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param mode 
 * @param shareFactor 
 * @param type 
 */
data class Apiv1wallettransactionHoursSelection (
    val mode: kotlin.String? = null,
    val shareFactor: kotlin.String? = null,
    val type: kotlin.String? = null
) {

}

