/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param owner 
 * @param hours 
 * @param calculatedHours 
 * @param coins 
 * @param uxid 
 */
data class Apiv1exploreraddressInputs (
    val owner: kotlin.String? = null,
    val hours: kotlin.Long? = null,
    val calculatedHours: kotlin.Long? = null,
    val coins: kotlin.String? = null,
    val uxid: kotlin.String? = null
) {

}

