/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param unspents 
 * @param addresses 
 * @param password 
 * @param id 
 */
data class Apiv1wallettransactionWallet (
    val unspents: kotlin.Array<kotlin.String>? = null,
    val addresses: kotlin.Array<kotlin.String>? = null,
    val password: kotlin.String? = null,
    val id: kotlin.String? = null
) {

}

