/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param unconfirmed 
 * @param blockSeq 
 * @param label 
 * @param confirmed 
 */
data class Apiv1exploreraddressStatus (
    val unconfirmed: kotlin.Boolean? = null,
    val blockSeq: kotlin.Long? = null,
    val label: kotlin.Long? = null,
    val confirmed: kotlin.Boolean? = null
) {

}

