/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param hours 
 * @param address 
 * @param coins 
 */
data class Apiv1wallettransactionTo (
    val hours: kotlin.Long? = null,
    val address: kotlin.String? = null,
    val coins: kotlin.Long? = null
) {

}

