/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param filename 
 * @param encrypted 
 * @param cryptoType 
 * @param label 
 * @param type 
 * @param version 
 * @param coin 
 * @param timestamp 
 */
data class Apiv1walletsMeta (
    val filename: kotlin.String? = null,
    val encrypted: kotlin.Boolean? = null,
    val cryptoType: kotlin.String? = null,
    val label: kotlin.String? = null,
    val type: kotlin.String? = null,
    val version: kotlin.String? = null,
    val coin: kotlin.String? = null,
    val timestamp: kotlin.Int? = null
) {

}

