/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.InlineResponse2003UnconfirmedVerifyTransaction

import com.squareup.moshi.Json
/**
 * 
 * @param lastReceived 
 * @param lastSent 
 * @param outgoing 
 * @param mirror 
 * @param address 
 * @param listenPort 
 * @param isTrustedPeer 
 * @param connectedAt 
 * @param unconfirmedVerifyTransaction 
 * @param id 
 * @param state 
 * @param userAgent 
 * @param height 
 */
data class InlineResponse2003 (
    val lastReceived: kotlin.Long? = null,
    val lastSent: kotlin.Long? = null,
    val outgoing: kotlin.Boolean? = null,
    val mirror: kotlin.Int? = null,
    val address: kotlin.String? = null,
    val listenPort: kotlin.Int? = null,
    val isTrustedPeer: kotlin.Boolean? = null,
    val connectedAt: kotlin.Long? = null,
    val unconfirmedVerifyTransaction: InlineResponse2003UnconfirmedVerifyTransaction? = null,
    val id: kotlin.Long? = null,
    val state: InlineResponse2003.State? = null,
    val userAgent: kotlin.String? = null,
    val height: kotlin.Long? = null
) {

    /**
    * 
    * Values: pending,connected,introduced
    */
    enum class State(val value: kotlin.String){
    
        @Json(name = "pending") pending("pending"),
    
        @Json(name = "connected") connected("connected"),
    
        @Json(name = "introduced") introduced("introduced");
    
    }

}

