/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.Apiv1walletsEntries
import skycoin.models.Apiv1walletsMeta

/**
 * 
 * @param entries 
 * @param meta 
 */
data class InlineResponse2005 (
    val entries: kotlin.Array<Apiv1walletsEntries>? = null,
    val meta: Apiv1walletsMeta? = null
) {

}

