/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param address 
 */
data class InlineResponse2006 (
    val address: kotlin.String? = null
) {

}

