/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * 
 * @param hours 
 * @param coins 
 * @param uxid 
 * @param ownerAddress 
 * @param spentBlockSeq 
 * @param spentTx 
 * @param time 
 * @param srcBlockSeq 
 * @param srcTx 
 */
data class InlineResponse200 (
    val hours: kotlin.Long? = null,
    val coins: kotlin.Int? = null,
    val uxid: kotlin.String? = null,
    val ownerAddress: kotlin.String? = null,
    val spentBlockSeq: kotlin.Int? = null,
    val spentTx: kotlin.String? = null,
    val time: kotlin.Long? = null,
    val srcBlockSeq: kotlin.Long? = null,
    val srcTx: kotlin.String? = null
) {

}

