/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.InlineResponse2007Data

/**
 * 
 * @param &#x60;data&#x60; 
 * @param error 
 */
data class InlineResponse2007 (
    val `data`: InlineResponse2007Data? = null,
    val error: kotlin.Any? = null
) {

}

