/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models


/**
 * Represent unconfirmed transactions
 * @param burnFactor 
 * @param maxTransactionSize 
 * @param maxDecimals 
 */
data class InlineResponse2003UnconfirmedVerifyTransaction (
    val burnFactor: kotlin.Int? = null,
    val maxTransactionSize: kotlin.Int? = null,
    val maxDecimals: kotlin.Int? = null
) {

}

