/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.Apiv1exploreraddressInputs
import skycoin.models.Apiv1exploreraddressOutputs
import skycoin.models.Apiv1exploreraddressStatus

/**
 * 
 * @param outputs 
 * @param innerHash 
 * @param inputs 
 * @param fee 
 * @param sigs 
 * @param length 
 * @param txid 
 * @param type 
 * @param status 
 * @param timestamp 
 */
data class InlineResponse2002 (
    val outputs: kotlin.Array<Apiv1exploreraddressOutputs>? = null,
    val innerHash: kotlin.String? = null,
    val inputs: kotlin.Array<Apiv1exploreraddressInputs>? = null,
    val fee: kotlin.Int? = null,
    val sigs: kotlin.Array<kotlin.String>? = null,
    val length: kotlin.Long? = null,
    val txid: kotlin.String? = null,
    val type: kotlin.Int? = null,
    val status: Apiv1exploreraddressStatus? = null,
    val timestamp: kotlin.Int? = null
) {

}

