/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.Apiv1pendingTxsTransaction

/**
 * 
 * @param announced 
 * @param isValid 
 * @param checked 
 * @param received 
 * @param transaction 
 */
data class InlineResponse2004 (
    val announced: kotlin.String? = null,
    val isValid: kotlin.Boolean? = null,
    val checked: kotlin.String? = null,
    val received: kotlin.String? = null,
    val transaction: Apiv1pendingTxsTransaction? = null
) {

}

