/**
* Skycoin REST API.
* Skycoin is a next-generation cryptocurrency.
*
* OpenAPI spec version: 0.25.1
* Contact: skycoin.doe@example.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package skycoin.models

import skycoin.models.Apiv1wallettransactionHoursSelection
import skycoin.models.Apiv1wallettransactionTo
import skycoin.models.Apiv1wallettransactionWallet

/**
 * 
 * @param changeAddress 
 * @param hoursSelection 
 * @param ignoreUnconfirmed 
 * @param to 
 * @param wallet 
 */
data class InlineObject (
    val changeAddress: kotlin.String? = null,
    val hoursSelection: Apiv1wallettransactionHoursSelection? = null,
    val ignoreUnconfirmed: kotlin.Boolean? = null,
    val to: kotlin.Array<Apiv1wallettransactionTo>? = null,
    val wallet: Apiv1wallettransactionWallet? = null
) {

}

